In [1]:
import zfit

/Users/mariehartmann/opt/anaconda3/envs/myenv38/lib/python3.8/site-packages/zfit/__init__.py:48: UserWarning: TensorFlow warnings are by default suppressed by zfit. In order to show them, set the environment variable ZFIT_DISABLE_TF_WARNINGS=0. In order to suppress the TensorFlow warnings AND this warning, set ZFIT_DISABLE_TF_WARNINGS=1.
  warnings.warn("TensorFlow warnings are by default suppressed by zfit."
/Users/mariehartmann/opt/anaconda3/envs/myenv38/lib/python3.8/site-packages/zfit/util/execution.py:73: UserWarning: Not running on Linux. Determining available cpus for thread can failand be overestimated. Workaround (only if too many cpus are used):`zfit.run.set_n_cpu(your_cpu_number)`
  warnings.warn("Not running on Linux. Determining available cpus for thread can fail"


In [2]:
import tensorflow as tf

### Model

In [30]:
obs1 = zfit.Space('x', limits=(0, 10))
obs2 = zfit.Space('y', limits=(5, 11))

In [31]:
mu1 = zfit.Parameter("mu1", 1.)
sigma1 = zfit.Parameter("sigma1", 1.)

mu2 = zfit.Parameter("mu2", 1.)
sigma2 = zfit.Parameter("sigma2", 1.)

In [33]:
gauss1 = zfit.pdf.Gauss(obs=obs1, mu=mu1, sigma=sigma1)
gauss2 = zfit.pdf.Gauss(obs=obs2, mu=mu2, sigma=sigma2)

In [34]:
gauss_2D = zfit.pdf.ProductPDF(pdfs=[gauss1,gauss2])

In [36]:
gauss_2D.obs

('x', 'y')

In [40]:
gauss_2D.pdfs

[<zfit.<class 'zfit.models.dist_tfp.Gauss'>  params=[mu1, sigma1],
 <zfit.<class 'zfit.models.dist_tfp.Gauss'>  params=[mu2, sigma2]]

In [44]:
gauss_2D.params

OrderedDict()

In [45]:
obs3 = zfit.Space('x', limits=(9,15))

In [46]:
mu3 = zfit.Parameter('mu3', 2.)
sigma3 = zfit.Parameter('sigma3', 3.)

In [47]:
gauss3 = zfit.pdf.Gauss(obs=obs3, mu=mu3, sigma=sigma3)

In [49]:
double_gauss = zfit.pdf.SumPDF(pdfs=[gauss1, gauss3], fracs = 0.3)
#pour que ça marche, il faut que les pdfs soient définies dans le même espace observable

NormRangeUnderdefinedError: Daughter pdfs [<zfit.<class 'zfit.models.dist_tfp.Gauss'>  params=[mu1, sigma1], <zfit.<class 'zfit.models.dist_tfp.Gauss'>  params=[mu3, sigma3]] do not agree on a `norm_range` and/or no `norm_range`has been explicitly set.

In [51]:
mu4 = mu3
sigma4 = sigma3
gauss4 = zfit.pdf.Gauss(obs=obs1, mu=mu4, sigma=sigma4)

In [53]:
double_gauss_bis = zfit.pdf.SumPDF(pdfs=[gauss1, gauss4], fracs=0.3)

In [55]:
double_gauss_bis

<zfit.<class 'zfit.models.functor.SumPDF'>  params=[Composed_autoparam_3, FIXED_autoparam_2]

### Parameters

In [3]:
#param1 = zfit.Parameter('a',5,2,10)

In [4]:
print(param1)

<zfit.Parameter 'a' floating=True value=5>


In [5]:
param1.name #le nom

'a'

In [7]:
param1.upper_limit #la limite supérieure

<tf.Tensor: shape=(), dtype=float64, numpy=10.0>

In [9]:
param1.lower_limit #la limite inférieure

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [12]:
param1.value() #la valeur

<tf.Tensor: shape=(), dtype=float64, numpy=5.0>

In [13]:
param2 = zfit.Parameter('b',5,2,10,step_size=0.01)

In [16]:
param2.step_size

<tf.Tensor: shape=(), dtype=float64, numpy=0.009999999776482582>

In [17]:
param3 = zfit.Parameter('c', 1)

In [18]:
def function (b,c) :
    return 2*b + c

In [20]:
param4 = zfit.ComposedParameter('e', function, params=[param2,param3] )

In [21]:
print(param4)

<zfit.ComposedParameter 'e' params=OrderedDict([('param_0', <zfit.Parameter 'b' floating=True value=5>), ('param_1', <zfit.Parameter 'c' floating=True value=1>)]) value=11>


In [22]:
param4.value()

<tf.Tensor: shape=(), dtype=float64, numpy=11.0>

In [24]:
param4.upper_limit() #même si b a une upper limit, d n'en hérite pas

AttributeError: 'ComposedParameter' object has no attribute 'upper_limit'

### Building a model

In [25]:
print(zfit.pdf.__all__)

['BasePDF', 'BaseFunctor', 'Exponential', 'CrystalBall', 'DoubleCB', 'Gauss', 'Uniform', 'TruncatedGauss', 'WrapDistribution', 'Cauchy', 'Poisson', 'Chebyshev', 'Legendre', 'Chebyshev2', 'Hermite', 'Laguerre', 'RecursivePolynomial', 'ProductPDF', 'SumPDF', 'GaussianKDE1DimV1', 'FFTConvPDFV1', 'ConditionalPDFV1', 'ZPDF', 'SimplePDF', 'SimpleFunctorPDF']


In [63]:
print(get_PARAMS(zfit.pdf.Gauss))

NameError: name 'get_PARAMS' is not defined